import Vue from "vue"
import "./fonts"
import Elevate from "./brand/elevate.vue";
import ElevateBackground from "./brand/elevateBackground.vue";
import ElevateBar from "./brand/elevateBar.vue";
import ElevateButton from "./brand/elevateButton.vue";
import ElevateCard from "./brand/elevateCard.vue";
import ElevateCodeEditor from "./brand/elevateCodeEditor.vue";
import ElevateColumn from "./brand/elevateColumn.vue";
import ElevateContent from "./brand/elevateContent.vue";
import ElevateDiagramBlock from "./brand/elevateDiagramBlock.vue";
import ElevateError from "./brand/elevateError.vue";
import ElevateFlatTotem from "./brand/elevateFlatTotem.vue";
import ElevateIndicator from "./brand/elevateIndicator.vue";
import ElevateLoader from "./brand/elevateLoader.vue";
import ElevateLogo from "./brand/elevateLogo.vue";
import ElevatePathName from "./brand/elevatePathName.vue";
import ElevateRow from "./brand/elevateRow.vue";
import ElevateScrollList from "./brand/elevateScrollList.vue";
import ElevateSocketDeath from "./brand/elevateSocketDeath.vue";
import ElevateStillTotem from "./brand/elevateStillTotem.vue";
import ElevateTotem from "./brand/elevateTotem.vue";
import ElevateTreeNode from "./brand/elevateTreeNode.vue";
import ElevateViewer from "./brand/elevateViewer.vue";

Vue.component("elevate", Elevate);
Vue.component("elevate-background", ElevateBackground);
Vue.component("elevate-bar", ElevateBar);
Vue.component("elevate-button", ElevateButton);
Vue.component("elevate-card", ElevateCard);
Vue.component("elevate-code-editor", ElevateCodeEditor);
Vue.component("elevate-column", ElevateColumn);
Vue.component("elevate-content", ElevateContent);
Vue.component("elevate-diagram-block", ElevateDiagramBlock);
Vue.component("elevate-error", ElevateError);
Vue.component("elevate-flat-totem", ElevateFlatTotem);
Vue.component("elevate-indicator", ElevateIndicator);
Vue.component("elevate-loader", ElevateLoader);
Vue.component("elevate-logo", ElevateLogo);
Vue.component("elevate-path-name", ElevatePathName);
Vue.component("elevate-row", ElevateRow);
Vue.component("elevate-scroll-list", ElevateScrollList);
Vue.component("elevate-socket-death", ElevateSocketDeath);
Vue.component("elevate-still-totem", ElevateStillTotem);
Vue.component("elevate-totem", ElevateTotem);
Vue.component("elevate-tree-node", ElevateTreeNode);
Vue.component("elevate-viewer", ElevateViewer);
